---
nepali_packages:
  - scim-tables-additional
  - fonts-sil-annapurna
  - fonts-lohit-deva-nepali
  - fonts-samyak-deva
  - fonts-lohit-deva
  - fonts-deva-extra
  - firefox-locale-ne
  - typecatcher
