---
- hosts: all
  vars:
    destdir: "$HOME/tmp/test"
    flatpak_dir: "/var/lib/flatpak/exports/share/applications"
    snap_dir: "/var/lib/flatpak/exports/share/applications"
    apt_dir: "/usr/share/applications"
    target_files:
      - gvim
      - com.spotify.Client
      - code
      - firefox

  tasks:
  - name: Creating directory if needed
    file:
      path: "{{ destdir }}"
      state: directory

  - name: Check apt installs
    stat:
      path: "{{ apt_dir }}/{{ item }}.desktop"
    register: apt_stat_results
    with_items: "{{ target_files }}"
    ignore_errors: True

  - name: Check snap installs
    stat:
      path: "{{ snap_dir }}/{{ item }}.desktop"
    register: snap_stat_results
    with_items: "{{ target_files }}"
    ignore_errors: True

  - name: Check flatpak installs
    stat:
      path: "{{ flatpak_dir }}/{{ item }}.desktop"
    register: flatpak_stat_results
    with_items: "{{ target_files }}"
    ignore_errors: True

  - name: Creating a file with content
    copy:
      dest: "{{ destdir }}/{{ item.item }}.dockitem"
      content: |
        [PlankDockItemPreferences]
        Launcher=file://{{item.stat.path}}
    with_items: "{{ apt_stat_results.results | union(flatpak_stat_results.results)  | union(snap_stat_results.results)}}"
    when: item.stat.exists == True