---
- name: Install Elementary OS specific packages
  gather_facts: true
  user: root
  hosts: all

  tasks:

      - name: Ubuntu Universe PPA
        apt_repository:
            repo: "deb http://archive.ubuntu.com/ubuntu bionic universe"
            state: present

      - name: Docker Key
        apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

      - name: Docker Repository
        apt_repository:
            repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
            state: present
            filename: docker

      - name: Typora Key
        apt_key:
            url: https://typora.io/linux/public-key.asc
            state: present

      - name: Typora Repository
        apt_repository:
            repo: 'deb https://typora.io/linux ./'
            state: present
            filename: docker

      - name: Ansible PPA
        apt_repository:
            repo: ppa:ansible/ansible
            state: present
            filename: ansible

      - name: Nextcloud PPA
        apt_repository:
            repo: ppa:nextcloud-devs/client
            state: present
            filename: nextcloud

      - name: Brave Key
        apt_key:
            url: https://brave-browser-apt-release.s3.brave.com/brave-core.asc
            state: present

      - name: Brave Repository
        apt_repository:
            repo: "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main"
            state: present
            filename: brave

      - name: VSCode Key
        apt_key:
            url: https://packages.microsoft.com/keys/microsoft.asc
            state: present

      - name: VSCode Trusted GPG Key
        shell: |
            curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
            install -o root -g root -m 644 packages.microsoft.gpg /etc/apt/trusted.gpg.d/
        args:
            warn: false # turn warning off, since curl is part of a pipe here

      - name: VSCode Repository
        apt_repository:
            repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main"
            state: present
            filename: vscode

      - name: Spotify Key
        apt_key:
            url: https://download.spotify.com/debian/pubkey.gpg
            state: present

      - name: Spotify
        apt_repository:
            repo: "deb http://repository.spotify.com stable non-free"
            state: present
            filename: spotify

      - name: Install freeoffice from deb
        apt:
            deb: https://www.freeoffice.com/download.php?filename=https://www.softmaker.net/down/softmaker-freeoffice-2018_976-01_amd64.deb

      - name: Add freeoffice repository using script in installed deb
        command: /usr/share/freeoffice2018/add_apt_repo.sh

      - name: Upgrade Packages (including ansible)
        apt:
            update_cache: yes
            upgrade: yes

      - name: Install Packages
        apt:
          pkg:
            #powertools
              - ansible
              - snapd
              - pass
              - encfs
              - cryfs
              - docker-ce
              - docker-ce-cli
              - docker-compose
              - containerd.io
              - net-tools
              #useful desktop tools
              - typora
              - nextcloud-client
              - brave-browser
              - code
              - spotify-client
              # elementary OS apps
              - com.github.alainm23.planner
              - com.github.babluboy.bookworm
              - com.github.lainsce.palaura
              - com.github.dr-styki.screenrec
              - com.github.lainsce.notejot
              #build tools
              - build-essential
              - cmake
              - clang
              - ninja-build
              - gdb
              - lldb-10
              - llvm-10*
              - make
              - python3-pip
              - pylint
              - lastpass-cli
              - cppcheck
              - cppcheck-gui
              - global
              - exuberant-ctags
              - autoconf
              - golang-go
              - valkyrie
              - google-mock
              - googletest
              # dependencies for hackmyresume
              - npm
              - wkhtmltopdf
              # Nepali fonts
              - scim-tables-additional
              - fonts-sil-annapurna
              - fonts-lohit-deva-nepali
              - fonts-samyak-deva
              - fonts-lohit-deva
              - fonts-deva-extra
              - firefox-locale-ne
              - typecatcher
              # Games
              - steam
              # Other
              - dconf-editor
              - unattended-upgrades
              - vim-gtk
              - screen
              - python
              - git
              - gitk
              - gpg

      - name: Install LXD from snap
        snap:
            name: lxd

      - name: Install Mailspring from snap
        snap:
            name: mailspring

      - name: Install Caprine from snap
        snap:
            name: caprine

      - name: Install Zoom from snap
        snap:
            name: zoom-client

      - name: Install Viber from deb
        apt:
          deb: https://download.cdn.viber.com/cdn/desktop/Linux/viber.deb

      - name: Install Dropbox from deb
        apt:
            deb: https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2020.03.04_amd64.deb

      - name: Install hackmyresume globally
        npm:
          name: hacksalot/hackmyresume
          global: yes
