---
- name: Install Elementary OS specific packages
  gather_facts: true
  user: root
  hosts: all
  vars_files:
    - [ "vars/{{ ansible_lsb.id }}_defaults.yml", "vars/ubuntu_defaults.yml" ]
    - [ "vars/{{ ansible_lsb.id }}_{{ansible_lsb.codename}}.yml", "vars/most_codenames.yml" ]

  tasks:
# Deprecate ansible ppa in favor of pip installation
# The reason being - we need some of the newer modules, but the ppa is not available
# for the latest ubuntu versions (20+) yet
      - name: Ansible PPA
        apt_repository:
            repo: ppa:ansible/ansible
            state: absent
            filename: ansible

      - name: Ubuntu Universe PPA
        apt_repository:
            repo: "deb http://archive.ubuntu.com/ubuntu {{ubuntu_codename}} universe"
            state: present

      - name: Docker Key
        apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

      - name: Docker Repository
        apt_repository:
            repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ubuntu_codename}} stable"
            filename: docker
            state: present

      - name: Jonathon F's PPA for latest vim
        apt_repository:
            repo: "ppa:jonathonf/vim"
            state: present
            filename: jonathonf

      - name: Brave Key
        apt_key:
            url: https://brave-browser-apt-release.s3.brave.com/brave-core.asc
            state: present

      - name: Brave Repository
        apt_repository:
            repo: "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main"
            state: present
            filename: brave

      - name: VSCode Key
        apt_key:
            url: https://packages.microsoft.com/keys/microsoft.asc
            state: present

      - name: VSCode Trusted GPG Key
        shell: |
            curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
            install -o root -g root -m 644 packages.microsoft.gpg /etc/apt/trusted.gpg.d/
        args:
            warn: false # turn warning off, since curl is part of a pipe here

      - name: VSCode Repository
        apt_repository:
            repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main"
            state: present
            filename: vscode

      - name: Add Insync Key From Ubuntu Keyserver
        apt_key:
            keyserver: keyserver.ubuntu.com
            id: ACCAF35C

      - name: Insync Repository
        apt_repository:
            repo: "deb http://apt.insync.io/ubuntu {{ubuntu_codename}} non-free contrib"
            state: present
            filename: insync

      - name: Check if my_package is installed
        command: dpkg-query -W softmaker-freeoffice-2018
        register: freeoffice2018_check_deb
        failed_when: freeoffice2018_check_deb.rc > 1
        changed_when: freeoffice2018_check_deb.rc == 1

      - name: Install freeoffice from deb
        apt:
            deb: https://www.freeoffice.com/download.php?filename=https://www.softmaker.net/down/softmaker-freeoffice-2018_976-01_amd64.deb
        when: freeoffice2018_check_deb.rc == 1

      - name: Add freeoffice repository using script in installed deb
        command: /usr/share/freeoffice2018/add_apt_repo.sh
        when: freeoffice2018_check_deb.rc == 1

      - name: Upgrade Packages
        apt:
            update_cache: 'True'
            upgrade: 'True'

      - name: Remove deprecated packages (migrate them to flatpak/pip to avoid adding new repositories)
        apt:
          pkg:
              - spotify-client
              - typora
              - nextcloud-client
              - dropbox
              - atom
              - viber
              - ansible
          state: absent

      - name: Remove Zoom from snap (deprecated -  now using flatpak)
        snap:
            name: zoom-client
            state: absent

      - name: Remove draw.io from snap (deprecated -  now using flatpak)
        snap:
            name: drawio
            state: absent

      - name: Install list of packages (newer method)
        apt: 
          name: "{{ distro_packages + release_packages }}"
          state: present

      - name: Install Packages (legacy method)
        apt:
          pkg:
            #powertools
              - ansible
              - python3-psutil
              - snapd
              - aptitude
              - flatpak
              - pass
              - encfs
              - cryfs
              - xdiskusage
              - docker-ce
              - docker-ce-cli
              - docker-compose
              - containerd.io
              - net-tools
              - graphviz
              - graphviz-doc
              - xdot
              - qemu-kvm
              - qemu
              - virt-manager
              - virt-viewer
              - imagemagick
              - imagemagick-common
              - imagemagick-doc
              - mc
              #useful desktop tools
              - brave-browser
              - qutebrowser
              - code
              - freeplane
              - calibre
              # Chess!!
              - stockfish
              - toga2
              - phalanx
              - pychess
              - scid
              # Mathematics
              - octave
              - wxmaxima
              #drivers
              - printer-driver-cjet
              #build tools
              - build-essential
              - cmake
              - clang
              - ninja-build
              - gdb
              - lldb-10
              - llvm-10*
              - make
              - python3-pip
              - pylint
              - lastpass-cli
              - cppcheck
              - cppcheck-gui
              - global
              - exuberant-ctags
              - autoconf
              - golang-go
              - google-mock
              - googletest
              - sqlite3
              - sqlite3-doc
              - sqlitebrowser
              # dependencies for hackmyresume
              - npm
              - wkhtmltopdf
              # Nepali fonts
              - scim-tables-additional
              - fonts-sil-annapurna
              - fonts-lohit-deva-nepali
              - fonts-samyak-deva
              - fonts-lohit-deva
              - fonts-deva-extra
              - firefox-locale-ne
              - typecatcher
              - pandoc
              # Other
              - dconf-editor
              - unattended-upgrades
              # using the default PPA - I use vim-gtk.
              # However, with ppa:jonathonf - vim-gtk3 and vim-nox are needed for newest features.
              - vim-gtk3
              - vim-nox
              - screen
              - python
              - git
              - gitk
              - gpg
              # I'd love to stick to the default night-light settings only
              # but there are known issues with multi-monitor setups.  Redshift-gtk works perfectly however.
              - redshift-gtk
              - insync

      - name: Hide libvert-qemu user from login screen
        copy:
            src: "elementary/system/AccountServices/system-user"
            dest: "/var/lib/AccountsService/users/libvirt-qemu"

#flatpak candidates:
#dropbox, viber, zoom, draw.io, wpsoffice

############################ Flatpak installations ############################ 

#First - add flathub repository if not yet present
      - name: Add the flathub flatpak repository remote to the user installation
        flatpak_remote:
          name: flathub
          state: present
          flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

      - name: Install Zoom from flatpak
        community.general.flatpak:
          name: us.zoom.Zoom
          state: present

      - name: Install draw.io from flatpak
        community.general.flatpak:
          name: com.jgraph.drawio.desktop
          state: present

      - name: Install Viber from flatpak
        community.general.flatpak:
          name: com.viber.Viber
          state: present

      - name: Install Dropbox from flatpak
        community.general.flatpak:
          name: com.dropbox.Client
          state: present

      - name: Install Typora from flatpak
        community.general.flatpak:
          name: io.typora.Typora
          state: present

      - name: Install Mark Text from flatpak
        community.general.flatpak:
          name: com.github.marktext.marktext
          state: present

      - name: Install Spotify from flatpak
        community.general.flatpak:
          name: com.spotify.Client
          state: present

      - name: Install Atom from flatpak
        community.general.flatpak:
          name: io.atom.Atom
          state: present

      - name: Install WPS Office from flatpak
        community.general.flatpak:
          name: com.wps.Office
          state: present

      - name: Install Franz messaging app from flatpak
        community.general.flatpak:
          name: com.meetfranz.Franz
          state: present

      - name: Install Pycharm Community from flatpak
        community.general.flatpak:
          name: com.jetbrains.PyCharm-Community
          state: present

############################ End Flatpak installations ############################ 

############################ Snap installations ############################ 

      - name: Install LXD from snap
        snap:
            name: lxd

      - name: Install Mailspring from snap
        snap:
            name: mailspring

      - name: Install Caprine from snap
        snap:
            name: caprine

############################ End Snap installations ############################ 

############################ NPM installations ############################ 
      - name: Install hackmyresume globally
        npm:
          name: hacksalot/hackmyresume
          global: yes

      - name: Install gitbook globally
        npm:
          name: gitbook-cli
          global: yes

############################ End NPM installations ############################ 
