---
- name: Elementary OS Desktop Configuration for user
  gather_facts: true
  hosts: all
  become: no
  vars:
    plank_dockitems_path: "$HOME/.config/plank/dock1/launchers/"
    #If this file exists - we will not try to configure dock
    plank_check_file: "mailspring_mailspring.dockitem"
    autostart_items_path: "$HOME/.config/autostart"
    global_autostart: "/etc/skel/.config/autostart"
    global_dockitems_path: "/etc/skel/.config/plank/dock1/launchers"

  tasks:
    - name: Copy AutoStart Items
      copy:
        src: "{{ item }}"
        dest: "{{ autostart_items_path }}"
      with_fileglob:
        - "files/elementary/autostart/*"

    - name: Create global autostart template directory
      become: true
      file:
        path: "{{item}}"
        state: directory
        owner: root
        group: root
      loop:
        - "{{global_autostart}}"
        - "{{global_dockitems_path}}"

#TODO - this should be loopable with the block above (per user) rather than a copy paste
    - name: Copy Global AutoStart Items
      become: true
      copy:
        src: "{{ item }}"
        dest: "{{ global_autostart }}"
        owner: root
        group: root
      with_fileglob:
        - "files/elementary/autostart/*"

    - name: Check if we should try to update plank dockitems
      stat:
        path: "{{ plank_dockitems_path }}/{{ plank_check_file }}"
      register: plankItems_check

- import_playbook: elementary_update_default_apps.yml

- import_playbook: ubuntu_desktop_configuration.yml
  when: ansible_lsb.id == "Ubuntu"

- import_playbook: plank_dockitems.yml
  when: not plankItems_check.stat.exists

- import_playbook: dconf_generation.yml