---
- name: Elementary OS Desktop Configuration for user
  gather_facts: true
  hosts: all
  become: no
  vars:
      plank_dockitems_path: "$HOME/.config/plank/dock1/launchers"
      plank_dockitems_to_remove: [ "org.pantheon.mail.dockitem", "org.gnome.Epiphany.dockitem" ]

  tasks:
      - name: Add Nepali Keyboard Layout
        command: gsettings set org.gnome.desktop.input-sources sources "[('xkb', 'us'), ('xkb', 'np')]"

      - name: Make Window Tiling and Desktop Switching Keys Mimic Windows
        shell: |
            gsettings set org.gnome.mutter.keybindings toggle-tiled-left "['<Super>Left']";
            gsettings set org.gnome.mutter.keybindings toggle-tiled-right "['<Super>Right']";
            gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-left "['<Control><Super>Left']";
            gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-right "['<Control><Super>Right']";

      - name: Enable night-light, set it to automatic schedule
        shell: |
            gsettings set org.gnome.settings-daemon.plugins.color night-light-enabled "true"
            gsettings set org.gnome.settings-daemon.plugins.color night-light-schedule-automatic "true"

      - name: Set dock icon size to small
        command: dconf write /net/launchpad/plank/docks/dock1/icon-size 32

      - name: Remove Some Launcher items glob
        file:
            path: "{{ plank_dockitems_path }}/{{ item }}"
            state: absent
        with_items: "{{ plank_dockitems_to_remove }}"

      - name: Copy Launcher items
        copy:
            src: "{{ item }}"
            dest: "{{ plank_dockitems_path }}"
        with_fileglob:
            - "files/elementary/launchers/*"
