---
- name: Ubuntu OS Desktop Configuration for user
  gather_facts: true
  hosts: all
  become: no

  vars:
    autostart_items_path: "$HOME/.config/autostart"
    global_autostart: "/etc/skel/.config/autostart"

  tasks:
    - name: Hide the Ubuntu dock
      command: gsettings set net.launchpad.plank.dock.settings:/net/launchpad/plank/docks/dock1/ show-dock-item false

    - name: Copy AutoStart Items
      copy:
        src: "{{ item }}"
        dest: "{{ autostart_items_path }}"
      with_fileglob:
        - "files/ubuntu/autostart/*"

    - name: Copy Global AutoStart Items
      become: true
      copy:
        src: "{{ item }}"
        dest: "{{ global_autostart }}"
        owner: root
        group: root
      with_fileglob:
        - "files/ubuntu/autostart/*"

    - name: Skip Welcome Screen for New Users
      become: true
      copy:
        dest: "/etc/skel/.config/gnome-initial-setup-done"
        content: "yes"
        owner: root
        group: root


