---
- name: VSCode plugins installation for user
  gather_facts: true
  hosts: all
  become: no
  vars:
      vscode_extensions_list: [ "golang.go", 
      "ms-azuretools.vscode-docker",
      "ms-python.python",
      "ms-python.vscode-pylance",
      "ms-vscode.cmake-tools",
      "ms-vscode.cpptools",
      "ms-vscode.Theme-1337",
      "VisualStudioExptTeam.vscodeintellicode",
      "vscodevim.vim",
      "vscoss.vscode-ansible",
      "xaver.clang-format" ]

  tasks:
      - name: Install VSCode Extensions
        command: code --install-extension {{ item }}
        with_items: "{{ vscode_extensions_list }}"
