---
- name: VSCode plugins installation for user
  gather_facts: true
  hosts: all
  become: no
  vars:
      vscode_extensions_list: [
          "DavidAnson.vscode-markdownlint",
          "eamodio.gitlens",
          "formulahendry.code-runner",
          "go2sh.cmake-integration-vscode",
          "golang.go",
          "inu1255.easy-snippet",
          "jebbs.plantuml",
          "LeetCode.vscode-leetcode",
          "ms-azuretools.vscode-docker",
          "ms-python.python",
          "ms-python.vscode-pylance",
          "ms-toolsai.jupyter",
          "ms-vscode.cmake-tools",
          "ms-vscode.cpptools",
          "ms-vscode-remote.remote-containers",
          "ms-vscode.Theme-1337",
          "mtxr.sqltools",
          "mtxr.sqltools-driver-mysql",
          "mtxr.sqltools-driver-sqlite",
          "shd101wyy.markdown-preview-enhanced",
          "twxs.cmake",
          "VisualStudioExptTeam.vscodeintellicode",
          "vscodevim.vim",
          "wangtao0101.debug-leetcode",
          "xaver.clang-format",
          "XavierCai.vscode-leetcode-cpp-debug"
          ]

  tasks:
      - name: Install VSCode Extensions
        command: code --install-extension {{ item }}
        with_items: "{{ vscode_extensions_list }}"
